FROM ubuntu:20.04
LABEL maintainer="indahhhre@gmail.com"
RUN apt-get update
RUN WORKDIR /home/coba
RUN echo "Selamat datang di Container Evaluasi" > file.txt
CMD ["echo", "Ini adalah Container Evaluasi"]